### ISSUE TITLE
Throws a `NullPointerException` during `sbt compile`

### ISSUE THREAD

**Issue by nhooey** [jbruggem/sbt-multiproject-example#1]
This happens with a recent version of SBT:
```
$ sbt compile
# ...
[info] Loading project definition from sbt-multiproject-example/project
java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
        at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1130)
        at java.base/java.util.regex.Pattern.split(Pattern.java:1249)
        at java.base/java.util.regex.Pattern.split(Pattern.java:1322)
        at sbt.IO$.pathSplit(IO.scala:723)
        at sbt.IO$.parseClasspath(IO.scala:821)
        at sbt.compiler.CompilerArguments.extClasspath(CompilerArguments.scala:64)
        at sbt.compiler.AggressiveCompile.withBootclasspath(AggressiveCompile.scala:50)
        at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:83)
        at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70)
        at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:45)
        at sbt.Compiler$.apply(Compiler.scala:70)
        at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:722)
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:716)
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:716)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
[error] (compile:compile) java.lang.NullPointerException
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

SBT version information:
```
$ brew info sbt
sbt: stable 1.2.1
Build tool for Scala projects
https://www.scala-sbt.org/
/usr/local/Cellar/sbt/1.1.2 (494 files, 48.5MB)
  Built from source on 2018-04-09 at 17:18:06
/usr/local/Cellar/sbt/1.1.4 (500 files, 48.6MB)
  Built from source on 2018-04-23 at 12:01:09
/usr/local/Cellar/sbt/1.1.5 (500 files, 52.5MB)
  Built from source on 2018-05-25 at 13:50:16
/usr/local/Cellar/sbt/1.1.6 (500 files, 52.5MB)
  Built from source on 2018-05-29 at 14:12:48
/usr/local/Cellar/sbt/1.2.1 (512 files, 49.4MB) *
  Built from source on 2018-08-14 at 09:42:37
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/sbt.rb
==> Requirements
Required: java >= 1.8 ✔
==> Caveats
You can use $SBT_OPTS to pass additional JVM options to sbt.
Project specific options should be placed in .sbtopts in the root of your project.
Global settings should be placed in /usr/local/etc/sbtopts
```

**Comment by jbruggem** [comment]
Hi nhooey,

thanks for your interest. As you can see [here](https://github.com/jbruggem/sbt-multiproject-example/blob/master/project/build.properties), this scaffold was written for `sbt` `0.13.0` (and probably a less recent version of java). I'd gladly welcome a PR if you wish to update it to a more recent version of `sbt`.

Given that this is just an example, it might be worth just starting from scratch, only taking inspiration from this old example.
